//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by list.rc
//
#define ID_DEFAULTS                     3
#define IDR_LISTMENU                    102
#define IDD_ABOUT                       111
#define IDR_LISTACC                     112
#define IDB_LISTLOGO                    119
#define IDI_ICON1                       120
#define IDI_ICON2                       123
#define IDM_VIEW_ALWAYSONTOP            124
#define IDM_VIEW_ASCIIJUNKFILTER        125
#define IDD_PREFSV2                     126
#define IDD_PREFS_GENERAL               129
#define IDD_PREFS_PARSING               129
#define IDD_PREFS_CACHING               130
#define IDD_PREFS_HIVE                  131
#define IDD_PREFS_DISPLAY               132
#define IDD_PREFS_SHELL                 133
#define IDD_PREFS_WINDOWS               133
#define IDB_RMBPIC                      134
#define IDD_PREFS_TAILING               138
#define IDD_NOTICE                      139
#define IDM_VIEW_TAILING                140
#define IDD_PREFS_UPDATES               142
#define IDD_UPDATE                      143
#define IDM_FILE_EDIT                   144
#define IDD_PREFS_SEARCHING             149
#define IDM_VIEW_HEXMODE_ENABLED        150
#define IDM_VIEW_HEXMODE_BYTES          151
#define IDM_VIEW_HEXMODE_WORDS          152
#define IDM_VIEW_HEXMODE_DWORDS         153
#define IDM_VIEW_HEXMODE_QWORDS         154
#define ID_HEXMODE_CONSTANTWIDTH        155
#define IDM_SEARCH_SETCURRENTLINE       156
#define IDB_BITMAP1                     159
#define IDI_ICON3                       160
#define IDI_LISTICON                    160
#define IDC_ALLOWNONCACHED              1000
#define IDC_NONCACHEDMINSIZE            1001
#define IDC_FILECACHESIZE               1002
#define IDC_NONCACHEDMINSIZE_SPIN       1003
#define IDC_FILECACHESIZE_SPIN          1004
#define IDC_LINECACHESIZE               1005
#define IDC_CACHECHUNKS                 1006
#define IDC_LINECACHESIZE_SPIN          1007
#define IDC_CACHECHUNKS_SPIN            1008
#define IDC_SEEKGRANULARITY             1009
#define IDC_BLOCKSIZELOG2               1010
#define IDC_SEEKGRANULARITY_SPIN        1011
#define IDC_BLOCKSIZELOG2_SPIN          1012
#define IDC_WRAPTEXT                    1013
#define IDC_ALPHAEDIT                   1014
#define IDC_TABSIZE                     1015
#define IDC_TABSIZE_SPIN                1016
#define IDC_ALPHA_SPIN                  1017
#define IDC_HIVEENABLED                 1018
#define IDC_FONTSELECT                  1019
#define IDC_FONTSIZESELECT              1020
#define ID_CANCEL                       1021
#define ID_OK                           1022
#define IDC_ANIMATEDSEARCH              1023
#define IDC_LISTXPVERSION               1024
#define IDC_DETECTPARSERS               1025
#define IDC_LISTXPABOUTTEXT             1026
#define IDC_ABOUTINFO                   1027
#define IDC_COLORLIST                   1028
#define ID_PICKCOLOR                    1029
#define IDC_TRANSCHECK                  1030
#define IDC_ALPHASTATIC                 1031
#define IDC_INTEGRATION                 1032
#define ID_HIVEBROWSE                   1033
#define IDC_HIVEPATH                    1034
#define IDC_TABCHOOSER                  1035
#define IDC_SECTION_PICKER              1036
#define ID_APPLY                        1037
#define IDC_SUBALIGN                    1038
#define IDC_SECTION_NAME                1039
#define IDC_HIVEBROWSE                  1040
#define IDC_HIVEMINSIZEKB               1041
#define IDC_HIVEMINSIZEKB_SPIN          1042
#define IDC_TRANSPARENT                 1043
#define IDC_ALPHALEVEL                  1044
#define IDC_ALPHALEVEL_SPIN             1045
#define IDC_FONTNAME                    1046
#define IDC_PICKCOLOR                   1047
#define IDC_FONTSIZE                    1048
#define IDC_ALPHALEVEL_SPIN2            1049
#define IDC_FONTSIZE_SPIN               1050
#define IDC_CHECK1                      1051
#define IDC_DISABLEUPDATES              1052
#define IDC_SHELLCHECKBOX               1053
#define IDC_HIGHLIGHTALL                1054
#define IDC_DISABLETAILWARNING          1055
#define IDC_SHELLINTEGRATION            1056
#define IDC_ALWAYSMAXIMIZE              1057
#define IDC_ALWAYSMAXIMIZED             1058
#define IDC_PREFETCHING                 1059
#define IDC_HIVECLEAR                   1060
#define IDC_HIVEINFOTEXT                1061
#define IDC_HIVESTATS                   1062
#define IDC_SEEKGRANULARITYLOG2         1063
#define IDC_SEEKGRANULARITYLOG2_SPIN    1064
#define IDC_RMBPIC                      1065
#define IDC_RMBEXPLAIN                  1066
#define IDC_CPUINFO                     1067
#define IDC_DISPLAYINFO                 1068
#define IDC_CACHINGEXPLAIN              1069
#define IDC_DONATE                      1070
#define IDC_IPAID                       1071
#define IDC_IPAIDEXPLAIN                1072
#define IDC_DONATEEXPLAIN               1073
#define IDC_GOTODONATE                  1074
#define IDC_JUSTKIDDING                 1075
#define IDC_TAILINGEXPLAIN              1076
#define IDC_DISABLEME                   1077
#define IDC_TEXTBODY                    1078
#define IDC_TAILING_INTERVAL_UNIT       1079
#define IDC_TAILING_INTERVAL            1080
#define IDC_TAILING_INTERVAL_SPIN       1081
#define IDC_TAILING_BACKTRACK           1082
#define IDC_TAILING_BACKTRACK_SPIN      1083
#define IDC_TAILING_FORCE_UPDATE        1084
#define IDC_TAILING_JUMP_TO_END         1085
#define IDC_IGNORE_PARSED_COLORS        1086
#define IDC_UPDATESEXPLAIN              1087
#define IDC_UPDATESENABLED              1088
#define IDC_UPDATESCHECKINTERVAL        1089
#define IDC_UPDATESCHECKINTERVAL_SPIN   1090
#define IDC_BUTTON1                     1091
#define IDC_CHANGEEDITPROGRAM           1092
#define IDC_UPDATENOW                   1093
#define IDC_YOURVERSION                 1094
#define IDC_LATESTVERSION               1095
#define IDC_UPDATEMESSAGE               1096
#define IDC_GOTOWEBSITE                 1097
#define IDC_REMINDLATER                 1098
#define IDC_UPDATESDAYSLEFT             1099
#define IDC_EDIT1                       1100
#define IDC_EDITPROGRAM                 1101
#define IDC_EDITEXPLAIN                 1102
#define IDC_UPDATESCHECKBOX             1103
#define IDC_SHELLEXPLAIN                1104
#define IDC_FIRSTTIMEINFO               1105
#define IDC_FIRSTTIMEEXPLAIN            1106
#define IDC_HIGHLIGHT_UNDERLINE         1107
#define IDC_HIGHLIGHT_INDIVIDUAL_TERMS  1108
#define IDC_SEARCHING_EXPLAIN           1109
#define IDC_HIGHLIGHT_ENTIRE_LINE       1110
#define IDC_HIVE_COMPRESSION            1112
#define ID_HELP_ABOUT                   40001
#define IDM_HELP_ABOUT                  40001
#define ID_FILE_EXIT                    40003
#define IDM_FILE_EXIT                   40003
#define IDM_FILE_PREFERENCES            40008
#define IDM_FILE_OPEN_NEW               40009
#define IDM_DISPLAY_HELP                40010
#define IDM_FILE_OPEN                   40011
#define IDM_VIEW_HEXMODE                40017
#define IDM_VIEW_FILEINFORMATION        40018
#define IDM_EDIT_COPY                   40021
#define IDM_EDIT_PASTE                  40022
#define IDM_VIEW_WRAPLINES              40023
#define IDM_SEARCH_FIND                 40025
#define IDM_SEARCH_LITERALSEARCH        40026
#define IDM_SEARCH_BOOLEANSEARCH        40027
#define IDM_SEARCH_REGEXSEARCH          40028
#define IDM_SEARCH_MATCHCASE            40031
#define IDM_SEARCH_FINDNEXT             40033
#define IDM_SEARCH_RESETSEARCH          40034
#define IDM_SEARCH_CANCELSEARCH         40035
#define IDM_SEARCH_ANIMATEDSEARCHES     40036
#define IDM_FILE_RESET                  40037
#define IDM_SEARCH_SEARCHDOWN           40038
#define IDM_SEARCH_SEARCHUP             40039
#define IDM_PARSERS_SENTINEL            40047
#define IDM_VIEW_TRANSPARENCY           40051
#define IDM_FILE_PREFERENCESV2          57607

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         40052
#define _APS_NEXT_CONTROL_VALUE         1113
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
